'use client';

import InfoPageShell from '@/components/InfoPageShell';

const sections = [
  {
    title: '1. Data We Collect',
    icon: 'database',
    description: 'Account credentials (email, password hash, security answers), device names, switch state logs, scheduling presets, and analytics data generated by your smart home nodes. We never collect raw AC load data or physical location beyond what you explicitly configure.'
  },
  {
    title: '2. How We Use Your Data',
    icon: 'insights',
    description: 'Your data powers the dashboard, real-time device control, activity logs, and energy analytics. We use aggregated, anonymized usage patterns to improve hardware reliability and product performance. We never sell personal data to third parties.'
  },
  {
    title: '3. Storage & Security',
    icon: 'lock',
    description: 'All data is hosted on Supabase with encrypted transport and secure authentication. Activity logs are automatically purged after 7 days. Passwords are hashed and never stored in plain text. Access to your control panel is protected by security-question verification and recovery codes.'
  },
  {
    title: '4. Cookies & Local Storage',
    icon: 'cookie',
    description: 'We use browser local storage to persist your theme preference and session tokens. No third-party advertising cookies are used on this site.'
  },
  {
    title: '5. Your Rights',
    icon: 'manage_accounts',
    description: 'You may export or delete your data at any time from your profile settings. To request data removal, contact us and we will action the request within 30 days.'
  },
  {
    title: '6. Policy Updates',
    icon: 'update',
    description: 'We may update this policy as the platform evolves. Significant changes will be announced on the dashboard and via the subscription newsletter.'
  }
];

export default function PrivacyPolicyPage() {
  return (
    <InfoPageShell
      badge="Legal"
      title="Privacy Policy"
      subtitle="How Electric Warriors collects, protects, and handles your data across the smart home platform."
    >
      <div className="max-w-3xl mx-auto flex flex-col gap-4">
        {sections.map((sec, index) => (
          <article key={index} className="p-6 md:p-7 bg-lp-surface-low border border-lp-outline-variant hover:border-lp-primary-container/35 transition-all rounded-xl flex gap-4 items-start">
            <span className="material-symbols-outlined text-lp-primary-container text-2xl mt-0.5 shrink-0">{sec.icon}</span>
            <div>
              <h3 className="font-label-caps text-sm font-bold text-white uppercase tracking-wider mb-2">{sec.title}</h3>
              <p className="text-xs font-body-md text-lp-on-surface-variant leading-relaxed">{sec.description}</p>
            </div>
          </article>
        ))}
      </div>
    </InfoPageShell>
  );
}