'use client';

import { useEffect, useState } from 'react';
import { Download, LockKeyhole, ShieldCheck } from 'lucide-react';

export default function SetupPage() {
  const [data, setData] = useState(null); const [error, setError] = useState('');
  useEffect(() => { fetch(`/api/provisioning/${window.location.pathname.split('/').pop()}`, { cache: 'no-store' }).then(async response => { const json = await response.json(); if (!response.ok) throw new Error(json.error || 'Setup link unavailable'); setData(json); }).catch(err => setError(err.message)); }, []);
  const download = () => { const blob = new Blob([data.firmware], { type: 'text/plain' }); const url = URL.createObjectURL(blob); const link = document.createElement('a'); link.href = url; link.download = data.fileName; link.click(); URL.revokeObjectURL(url); };
  return <main className="min-h-screen bg-background px-5 py-16 text-text sm:px-8"><div className="mx-auto max-w-xl">{error ? <div className="rounded-2xl border border-red-400/30 bg-card p-8 text-center"><LockKeyhole className="mx-auto text-red-400" size={30} /><h1 className="mt-4 text-2xl font-black">Setup link unavailable</h1><p className="mt-2 text-sm font-semibold text-text-muted">{error}</p></div> : !data ? <div className="py-24 text-center text-sm font-bold text-text-muted">Verifying secure setup link…</div> : <><div className="mb-8 text-center"><ShieldCheck className="mx-auto text-accent" size={34} /><p className="mt-5 text-[10px] font-black uppercase tracking-[.22em] text-accent">VikaTech secure provisioning</p><h1 className="mt-3 text-3xl font-black">Your ESP32 setup file</h1><p className="mt-3 text-sm font-semibold text-text-muted">This private link has been verified and can only be used once.</p></div><div className="space-y-3 rounded-2xl border border-border bg-card p-6 font-mono text-sm"><p><span className="text-text-muted">Board name</span><br /><b>{data.boardName}</b></p><p><span className="text-text-muted">Board identifier</span><br /><b>{data.boardIdentifier}</b></p><p><span className="text-text-muted">HOME-leader password</span><br /><b>{data.password}</b></p></div><button onClick={download} className="mt-5 flex w-full items-center justify-center gap-2 rounded-xl bg-accent px-4 py-3 text-xs font-black text-[var(--btn-text)] hover:bg-accent-hover"><Download size={16} /> Download generated ESP32 firmware</button><p className="mt-6 text-center text-[10px] font-semibold text-text-muted">For security, do not share this page or the downloaded file. The link is invalid after this page is opened.</p></>}</div></main>;
}
